openapi: 3.0.3
info:
  title: Viabirds Coding Challenge - Laravel
  version: 1.0.0
servers:
  - url: https://localhost:8000/api/
tags:
  - name: score
    description: Score for users
paths:
  /score:
    post:
      tags:
        - score
      summary: Create a new score
      description: Add a new score to the user
      requestBody:
        description: Create a new score
        content:
          application/json:
            schema:
              type: object
              properties:
                score:
                  type: integer
                  example: 10
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '409':
          description: Given user already has a score
components:
  schemas:
    User:
      required:
        - name
        - photoUrls
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        name:
          type: string
          example: "John Doe"
        score:
          type: integer
          example: 10
        created_at:
          type: string
          example: '2024-01-18T09:32:28Z'
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
